# 数据集与结果路径
data_path: "/root/GA/data/breast_cancer.csv"
results_dir: "/root/GA/results/breast_cancer_results_moga"
importances_path: "/root/GA/results/importances/breast_cancer"

# 特征数范围
min_features: 2
max_features: 50

# 随机种子列表
random_states:
  - 42
  - 123
  - 256
  - 114514
  - 3407
  - 5132
  - 5134
  - 5122
  - 5106
  - 1163

# 交叉验证设置
cv_mode: "kfold"
cv_k:   15

# 遗传算法超参数
n_max:    50
n_gen:    200
pop_size: 200
fs_prob:  1.25

# 特征选择方法权重分布
fs_distrib:
  mrmr:          0.125
  relieff:       0.125
  kruskalwallis: 0.125
  mutualinfo:    0.125
  decisiontree:  0.125
  anovafvalue:   0.125
  randomforest:  0.125
  lassocv:       0.125

# 评价器与指标
fitness_evaluator_name: "linearsvm"
fitness_target_metric:  "test_f1_macro"
target_metric:          "test_f1_macro"

# fitness_evaluator_obj = LinearSVC(max_iter=10000, dual=True, random_state=random_state)
# clfs = {"linearsvm": LinearSVC(max_iter=10000, dual=True, random_state=random_state)}
